name: Frontend and Backend testing

on:
  pull_request:
    branches: [ devDocker_v2 ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.1
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: cd __backend tests__ && npx jest --__config backend-tests__/jest.config.js --verbose