name: Frontend and Backend testing

on:
  pull_request:
    branches: [ devDocker_v2 ]

jobs:
  frontend_testing:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.1
      - run: npm ci
      - run: npm run build
      - run: npm run test

  backend_testing:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.1
      - run: npm ci
      - run: npm run build
      - run: npx jest --__config backend-tests__/jest.config.js --verbose
        working-directory: __backend-tests